    name: My Manual Workflow

    on:
      workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'info'
            type: choice
            options:
            - info
            - warning
            - debug
          environment:
            description: 'Environment to deploy to'
            required: true
            type: environment
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run a one-line script
            run: echo Hello, world!
          - name: Echo inputs
            run: |
              echo "Log Level: ${{ github.event.inputs.logLevel }}"
              echo "Environment: ${{ github.event.inputs.environment }}"
